### ISSUE TITLE
ニオイセンサ用の画面

### ISSUE THREAD

**Issue by toshi17** [jphacks/SD_1806#20]
ニオイセンサのモニタリング用画面

**Comment by toshi17** [comment]
<img src="https://user-images.githubusercontent.com/32355076/48448918-e3308380-e7e3-11e8-90eb-1cffda1706f9.gif" width=100>

**Comment by toshi17** [comment]
でかくてびびる、これ画像のサイズ調整どうやってするんや、、
Nakashimaのにおい画面への意見求む

**Comment by toshi17** [comment]
あと、円グラフverもある
<img src="https://user-images.githubusercontent.com/32355076/48449386-9b126080-e7e5-11e8-8bb9-faa3e4f40e61.png" width="100">

**Comment by Sidebook** [comment]
めっちゃええやん...

個人的には円グラフの方が好き
あとは、匂いの指数の絶対値じゃなくて、パーセンテージとか？
絶対値で出すなら、匂いセンサの仕様を調べてきちんとした単位に変換するのがいいかも（すでにそう？）

画像のサイズ調整はmarkdownはつまるとこhtmlだから<img>タグを直接書いてwidth指定すれば小さくできるよ

```
<img src="hogehoge.png" width="100px" />
```
<img src="https://user-images.githubusercontent.com/32355076/48449386-9b126080-e7e5-11e8-8bb9-faa3e4f40e61.png" width="100px" />

**Comment by toshi17** [comment]
とりまこんな感じでよい？
単位に変換して出すのよさげだけど、とりまパーセント表示で
<img src="https://user-images.githubusercontent.com/32355076/48461765-a7fc7780-e818-11e8-8db2-27b7d1075412.png" width="100">

**Comment by Sidebook** [comment]
自分で言ったけど100pxちっちぇえwww

わいはよいと思う！それにしてもフロント力の高まりがすごい
